#!/usr/bin/env bash
# This script configures Haproxy load balancer in a server.

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  V-ope-frontend
        bind *:80
        mode http
        default_backend V-ope-backend
backend ehoneah-backend
        balance roundrobin
        server 220193-web-01 54.167.198.237:80 check
        server 220193-web-02 18.210.33.189:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
