#!/usr/bin/env bash
#this script configures my ssh client so as to enaable me
#connect my server without using password

Host *
	HostName 54.167.198.237
	User ubuntu
	IdentityFile ~/.ssh/school
	PasswordAuthentication no
